# EDA - Energy Efficiency Dataset

In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler

def rmse(y_true, y_pred):
    output = np.sqrt(mean_squared_error(y_true, y_pred))
    return output

sns.set_theme(style="whitegrid")
plt.rcParams['figure.dpi'] = 110
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

### Import Dataset

In [22]:
# Import energy efficiency dataset
from ucimlrepo import fetch_ucirepo
  
# fetch dataset 
energy_efficiency = fetch_ucirepo(id=242) 
  
# data (as pandas dataframes) 
X = energy_efficiency.data.features 
y = energy_efficiency.data.targets 
  
# metadata 
print(energy_efficiency.metadata) 
  
# variable information 
print(energy_efficiency.variables)

{'uci_id': 242, 'name': 'Energy Efficiency', 'repository_url': 'https://archive.ics.uci.edu/dataset/242/energy+efficiency', 'data_url': 'https://archive.ics.uci.edu/static/public/242/data.csv', 'abstract': 'This study looked into assessing the heating load and cooling load requirements of buildings (that is, energy efficiency) as a function of building parameters.', 'area': 'Computer Science', 'tasks': ['Classification', 'Regression'], 'characteristics': ['Multivariate'], 'num_instances': 768, 'num_features': 8, 'feature_types': ['Integer', 'Real'], 'demographics': [], 'target_col': ['Y1', 'Y2'], 'index_col': None, 'has_missing_values': 'no', 'missing_values_symbol': None, 'year_of_dataset_creation': 2012, 'last_updated': 'Mon Feb 26 2024', 'dataset_doi': '10.24432/C51307', 'creators': ['Athanasios Tsanas', 'Angeliki Xifara'], 'intro_paper': {'ID': 379, 'type': 'NATIVE', 'title': 'Accurate quantitative estimation of energy performance of residential buildings using statistical machine learning tools', 'authors': 'A. Tsanas, Angeliki Xifara', 'venue': 'Energy and Buildings, vol. 49', 'year': 2012, 'journal': None, 'DOI': None, 'URL': 'https://www.semanticscholar.org/paper/Accurate-quantitative-estimation-of-energy-of-using-Tsanas-Xifara/719e65379c5959141180a45f540f707d583b8ce2', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'We perform energy analysis using 12 different building shapes simulated in Ecotect. The buildings differ with respect to the glazing area, the glazing area distribution, and the orientation, amongst other parameters. We simulate various settings as functions of the afore-mentioned characteristics to obtain 768 building shapes. The dataset comprises 768 samples and 8 features, aiming to predict two real valued responses. It can also be used as a multi-class classification problem if the response is rounded to the nearest integer.', 'purpose': None, 'funded_by': None, 'instances_represent': None, 'recommended_data_splits': None, 'sensitive_data': None, 'preprocessing_description': None, 'variable_info': 'The dataset contains eight attributes (or features, denoted by X1...X8) and two responses (or outcomes, denoted by y1 and y2). The aim is to use the eight features to predict each of the two responses.\r\n\r\nSpecifically:\r\nX1\tRelative Compactness\r\nX2\tSurface Area\r\nX3\tWall Area\r\nX4\tRoof Area\r\nX5\tOverall Height\r\nX6\tOrientation\r\nX7\tGlazing Area\r\nX8\tGlazing Area Distribution\r\ny1\tHeating Load\r\ny2\tCooling Load', 'citation': None}}
  name     role        type demographic                description units  \
0   X1  Feature  Continuous        None       Relative Compactness  None
1   X2  Feature  Continuous        None               Surface Area  None
2   X3  Feature  Continuous        None                  Wall Area  None
3   X4  Feature  Continuous        None                  Roof Area  None
4   X5  Feature  Continuous        None             Overall Height  None
5   X6  Feature     Integer        None                Orientation  None
6   X7  Feature  Continuous        None               Glazing Area  None
7   X8  Feature     Integer        None  Glazing Area Distribution  None
8   Y1   Target  Continuous        None               Heating Load  None
9   Y2   Target  Continuous        None               Cooling Load  None

  missing_values
0             no
1             no
2             no
3             no
4             no
5             no
6             no
7             no
8             no
9             no

### Read the Dataset Values for get an idea

- All X values

In [23]:
X.T

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
X1,0.98,0.98,0.98,0.98,0.9,0.9,0.9,0.9,0.86,0.86,...,0.66,0.66,0.64,0.64,0.64,0.64,0.62,0.62,0.62,0.62
X2,514.50,514.50,514.50,514.50,563.5,563.5,563.5,563.5,588.00,588.00,...,759.50,759.50,784.00,784.00,784.00,784.00,808.50,808.50,808.50,808.50
X3,294.00,294.00,294.00,294.00,318.5,318.5,318.5,318.5,294.00,294.00,...,318.50,318.50,343.00,343.00,343.00,343.00,367.50,367.50,367.50,367.50
X4,110.25,110.25,110.25,110.25,122.5,122.5,122.5,122.5,147.00,147.00,...,220.50,220.50,220.50,220.50,220.50,220.50,220.50,220.50,220.50,220.50
X5,7.00,7.00,7.00,7.00,7.0,7.0,7.0,7.0,7.00,7.00,...,3.50,3.50,3.50,3.50,3.50,3.50,3.50,3.50,3.50,3.50
X6,2.00,3.00,4.00,5.00,2.0,3.0,4.0,5.0,2.00,3.00,...,4.00,5.00,2.00,3.00,4.00,5.00,2.00,3.00,4.00,5.00
X7,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,...,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40
X8,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,...,5.00,5.00,5.00,5.00,5.00,5.00,5.00,5.00,5.00,5.00

- Two Target Values

In [25]:
y.T

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
Y1,15.55,15.55,15.55,15.55,20.84,21.46,20.71,19.68,19.5,19.95,...,14.92,15.16,17.69,18.19,18.16,17.88,16.54,16.44,16.48,16.64
Y2,21.33,21.33,21.33,21.33,28.28,25.38,25.16,29.60,27.3,21.97,...,17.55,18.06,20.82,20.21,20.71,21.40,16.88,17.11,16.61,16.03

### Remove the qualitative columns
- Because they do not provide a meaningful continuous output like other X variables and they are just like a categorical values. Section only focuses on quantitative variables

In [ ]:
clean_X = X.drop(['X6', 'X8'], axis=1)
df[clean_X]

,0,1,2,3,4,5,6,7,8,9,...,758,759,760,761,762,763,764,765,766,767
X1,0.98,0.98,0.98,0.98,0.9,0.9,0.9,0.9,0.86,0.86,...,0.66,0.66,0.64,0.64,0.64,0.64,0.62,0.62,0.62,0.62
X2,514.50,514.50,514.50,514.50,563.5,563.5,563.5,563.5,588.00,588.00,...,759.50,759.50,784.00,784.00,784.00,784.00,808.50,808.50,808.50,808.50
X3,294.00,294.00,294.00,294.00,318.5,318.5,318.5,318.5,294.00,294.00,...,318.50,318.50,343.00,343.00,343.00,343.00,367.50,367.50,367.50,367.50
X4,110.25,110.25,110.25,110.25,122.5,122.5,122.5,122.5,147.00,147.00,...,220.50,220.50,220.50,220.50,220.50,220.50,220.50,220.50,220.50,220.50
X5,7.00,7.00,7.00,7.00,7.0,7.0,7.0,7.0,7.00,7.00,...,3.50,3.50,3.50,3.50,3.50,3.50,3.50,3.50,3.50,3.50
X7,0.00,0.00,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,...,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40,0.40