In [15]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler

def rmse(y_true, y_pred):
    output = np.sqrt(mean_squared_error(y_true, y_pred))
    return output

sns.set_theme(style="whitegrid")
plt.rcParams['figure.dpi'] = 110
RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

In [18]:
import csv

data = pd.read_csv('mpg.csv', sep=',', quoting=csv.QUOTE_NONE)
data.head(10)

,"""mpg",cylinders,displacement,horsepower,weight,acceleration,model year,origin,"car name"""
0,"""18",8,307.0,130,3504,12.0,70,1,"chevrolet chevelle malibu"""
1,"""15",8,350.0,165,3693,11.5,70,1,"buick skylark 320"""
2,"""18",8,318.0,150,3436,11.0,70,1,"plymouth satellite"""
3,"""16",8,304.0,150,3433,12.0,70,1,"amc rebel sst"""
4,"""17",8,302.0,140,3449,10.5,70,1,"ford torino"""
5,"""15",8,429.0,198,4341,10.0,70,1,"ford galaxie 500"""
6,"""14",8,454.0,220,4354,9.0,70,1,"chevrolet impala"""
7,"""14",8,440.0,215,4312,8.5,70,1,"plymouth fury iii"""
8,"""14",8,455.0,225,4425,10.0,70,1,"pontiac catalina"""
9,"""15",8,390.0,190,3850,8.5,70,1,"amc ambassador dpl"""

In [27]:
df_clean = data.drop(columns=['origin','car name"']).dropna().reset_index(drop=True)
df_clean.head(10)

  "mpg  cylinders  displacement horsepower  weight  acceleration  model year
0  "18          8         307.0        130    3504          12.0          70
1  "15          8         350.0        165    3693          11.5          70
2  "18          8         318.0        150    3436          11.0          70
3  "16          8         304.0        150    3433          12.0          70
4  "17          8         302.0        140    3449          10.5          70
5  "15          8         429.0        198    4341          10.0          70
6  "14          8         454.0        220    4354           9.0          70
7  "14          8         440.0        215    4312           8.5          70
8  "14          8         455.0        225    4425          10.0          70
9  "15          8         390.0        190    3850           8.5          70

In [28]:
TARGET = 'mpg'
quan_candidates = ['displacement', 'horsepower', 'weight', 'acceleration', 'model year']
df_clean[quan_candidates]

     displacement horsepower  weight  acceleration  model year
0           307.0        130    3504          12.0          70
1           350.0        165    3693          11.5          70
2           318.0        150    3436          11.0          70
3           304.0        150    3433          12.0          70
4           302.0        140    3449          10.5          70
..            ...        ...     ...           ...         ...
393         140.0         86    2790          15.6          82
394          97.0         52    2130          24.6          82
395         135.0         84    2295          11.6          82
396         120.0         79    2625          18.6          82
397         119.0         82    2720          19.4          82

[398 rows x 5 columns]